require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*
  TargetRubyVersion: 3.3
  SuggestExtensions: false

Layout/HashAlignment:
  Enabled: true
  AllowMultipleStyles: true
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ArgumentsForwarding:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - config/routes.rb
  IncludedMacros:
    - post
    - get
    - put
    - patch
    - delete
  AllowedMethods:
    - prepend
    - include
    - to
    - not_to
    - describe

Style/RedundantConstantBase:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

# Rubocop RSpec
RSpec/ContextWording:
  Prefixes:
    - associations
    - validations
    - when
    - with
    - without

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
