name: "logistics_challenge"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
    - redis
    - postgres
  redis:
    image: redis:7.2
    networks:
    - default
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data
  postgres:
    image: postgres:16.1
    networks:
    - default
    volumes:
    - postgres-data:/var/lib/postgresql/data
    ports:
    - "5434:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  api_docs:
    image: swaggerapi/swagger-ui
    ports:
      - 3001:8080
    volumes:
      - ./:/usr/share/nginx/html/docs/
    environment:
      - "URLS_PRIMARY_NAME=Logistics API"
      - "URLS=[
          {url: '/docs/docs/api.yaml', name: 'Logistics API'},
        ]"
volumes:
  redis-data:
  postgres-data:
