
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: postgres
  username: postgres
  host: localhost
  port: 5434

development:
  <<: *default
  database: logistics_challenge_development

test:
  <<: *default
  database: logistics_challenge_test

production:
  <<: *default
  database: logistics_challenge_production
  username: logistics_challenge
  password: <%= ENV["LOGISTICS_CHALLENGE_DATABASE_PASSWORD"] %>
