openapi: 3.0.0
info:
  title: Logistics challenge API
  description: Documentation of logistics challenge API
  version: 1.0.0
tags:
  - name: orders
    description: Orders
  - name: order_products
    description: Order products
servers:
  - url: 'http://localhost:3000'
    description: Development server
paths:
  /order_products/import:
    post:
      tags:
       - order_products
      summary: Import Order Products
      description: Imports a list of order products from a file.
      operationId: orderProductsImport
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The data to be imported
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportOrderProductsResponse'
        400:
          description: Bab Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportOrderProductsResponseError'
components:
  schemas:
    ImportOrderProductsResponse:
      type: object
      properties:
        meta:
          type: object
          properties:
            info:
              type: string
              description: Success message
        data:
          type: object
      example:
        data: null
        meta:
          info: "The import process will run in the background."
    ImportOrderProductsResponseError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
                description: Error message
      example:
        errors:
          - title: "Error importing order product."
